s = f'{foo'
print(42)
raise Exception