from unittest import TestCase


class TestFoo(TestCase):
    def test_test(self):
        self.fail()
